-- Categorias
INSERT INTO categoria (id, nome) VALUES (1, 'Crime');
INSERT INTO categoria (id, nome) VALUES (2, 'Ficção Científica');
INSERT INTO categoria (id, nome) VALUES (3, 'Drama');
INSERT INTO categoria (id, nome) VALUES (4, 'Mistério');
INSERT INTO categoria (id, nome) VALUES (5, 'Suspense');
INSERT INTO categoria (id, nome) VALUES (6, 'Terror');
INSERT INTO categoria (id, nome) VALUES (7, 'Comédia');
INSERT INTO categoria (id, nome) VALUES (8, 'Aventura');

-- Filmes
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (1, 'Goodfellas', 'Ascensão e queda na máfia na visão de Henry Hill', 'Scorsese', 'https://th.bing.com/th/id/OIP.9WCTKVpfFCIeUidSEf18TAHaLH?w=208&h=305&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 1);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (2, 'Interestelar', 'Viagem espacial e relatividade', 'Christopher Nolan', 'https://media.themoviedb.org/t/p/w600_and_h900_face/6ricSDD83BClJsFdGB6x7cM0MFQ.jpg', 2);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (4, 'Shutter Island', 'Dicaprio desvendando mistérios', 'Scorsese', 'https://media.themoviedb.org/t/p/w600_and_h900_face/erl801HYIodoIBGZeFk0GTwCUBh.jpg', 4);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (5, 'The Irishman', 'De niro e Al Pacino na máfia', 'Scorsese', 'https://th.bing.com/th/id/OIP.3pRnFEUVMlGL5FDMiIkk_QHaLH?w=204&h=306&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 1);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (6, 'The Wolf of Wallstreet', 'Ascensão meteórica e queda de Jordan Belfort como stock broker', 'Scorsese', 'https://media.themoviedb.org/t/p/w600_and_h900_face/sIy0jXDkaMf3SDZGaWcmkC2IOl.jpg', 7);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (7, 'Raging Bull', 'Um talentoso boxeador cuja fúria e comportamento autodestrutivo corroem suas relações pessoais e carreira', 'Scorsese', 'https://th.bing.com/th/id/OIP.PLzClhGIlRvhoij5529W-gHaLH?w=208&h=305&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 3);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (8, 'Fight Club', 'Can''t talk about it', 'David Fincher', 'https://th.bing.com/th/id/OIP.VCFv9kYkADnQN4ms2c0dxgHaLH?w=204&h=306&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 3);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (9, 'The Godfather', 'O Poderoso Chefão acompanha a poderosa família mafiosa Corleone na Nova York do pós-guerra, revelando alianças, rivalidades e a transição de poder do patriarca Vito para o filho Michael', 'Coppola', 'https://th.bing.com/th/id/OIP.cxa0kYJ_qucjCQNBb0lKigHaLH?w=208&h=305&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 1);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (11, 'The Godfather Part II', 'O Poderoso Chefão: Parte II alterna entre a juventude de Vito Corleone e a consolidação de poder de Michael, agora líder da família nos anos 1950, explorando temas de ambição, lealdade e traição.', 'Coppola', 'https://th.bing.com/th/id/OIP.ux3uXgsliJokECEcHVAQrgHaKj?w=208&h=297&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 1);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (12, 'The Godfather Part III', 'O Poderoso Chefão: Parte III acompanha Michael Corleone, agora envelhecido, tentando legitimar os negócios da família e buscar redenção, enquanto lida com intrigas envolvendo o Vaticano, disputas de poder e um romance proibido que ameaça sua filha', 'Coppola', 'https://media.themoviedb.org/t/p/w600_and_h900_face/y8GROCjgD8amoFufSx2USKrOy7d.jpg', 1);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (13, 'Shawshank Redemption', 'Um Sonho de Liberdade é um aclamado filme de drama de 1994 que narra a história de esperança, amizade e resiliência dentro de uma prisão', 'Frank Darabont', 'https://media.themoviedb.org/t/p/w600_and_h900_face/umX3lBhHoTV7Lsci140Yr8VpXyN.jpg', 3);
INSERT INTO filme (id, titulo, descricao, diretor, imagem_url, categoria_id) VALUES (14, 'Taxi Driver', 'Taxi Driver acompanha Travis Bickle, um veterano solitário da Guerra do Vietnã que trabalha como taxista nas madrugadas de Nova York, imerso em um ambiente de decadência moral e criminalidade.', 'Scorsese', 'https://th.bing.com/th/id/OIP.4N9EMatlwSAvZUcwnVDrQwHaLH?w=208&h=305&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3', 3);